### ISSUE TITLE
Can't verify simple Yul contract due to parser error (that only occurs on Blockscout)

### ISSUE THREAD

**Issue by haltman-at** [blockscout/blockscout#7336]
Hi!  I saw that Blockscout now supports Yul contract verification, so I figured I'd test it out with a dead simple Yul contract.  However, verification failed with a compile error, even though the contract compiles fine on my machine.  No idea what's going wrong here.

(For context, if you're wondering: I work on Truffle and I'm testing this out because I'm trying to finally write that [Blockscout integration for Truffle](https://github.com/trufflesuite/truffle/issues/4779) that has been talked about for a while.  I filed a whole bunch of issues a while back that were blocking it, but those are finally solved, so I figured it was time to take another stab at it!  Of course, first I had to get up to date on Blockscout's current workings, and make sure there weren't any cases I was unaware of, which is when I encountered the Yul case and realized I had to make sure I knew how it worked before doing anything.  But, as you can see, my test of this case hit a snag!  So for now I still don't know how this case works.)

### Environment

I'm using the Goerli Blockscout deployment at https://eth-goerli.blockscout.com/

### Steps to reproduce

I'm attempting to verify the contract on Goerli at address 0x8F95fc67146d6c70D872FA53def7bB053FC7f1a1.  I'm doing this via the web interface ([link](https://eth-goerli.blockscout.com/address/0x8F95fc67146d6c70D872FA53def7bB053FC7f1a1/contract_verification)).

The contract verification method is Solidity (flattened).  The Yul box is checked.  Compiler version is 0.8.19.  EVM version is default.  Optimization is turned off.  There are no libraries.  The contract code is:

```yul
//SPDX-License-Identifier: MIT

object "ExternalTestYul" {
  code {
    let size := datasize("runtime")
    datacopy(0, dataoffset("runtime"), size)
    return(0, size)
  }
  object "runtime" {
    code {
      mstore(0, 1)
      return(0, 0x20)
    }
  }
}
```

This is, to be clear, the actual Yul code that I compiled the contract with on my machine.

### Expected behaviour

The contract should verify.

### Actual behaviour

I get the following error message:
```
Compilation error: ["ParserError: Expected identifier but got 'StringLiteral'\n --> .yul:3:8:\n |\n3 | object \"ExternalTestYul\" {\n | ^^^^^^^^^^^^^^^^^\n\n"]
```

I mean, I guess it's expecting `object` to be followed by an identifier rather than a string literal, but I'm very confused because
that is not how Yul works in 0.8.19, and indeed to my knowledge it has not ever worked that way; object names are, as far as I'm aware, supposed to be given as string literals and not identifiers.  And, again, this is the actual Yul code I compiled the contract from.  So I'm very confused as to why I'm getting an error here.

Thanks!
